In [1]:
%matplotlib inline
%load_ext autoreload

In [2]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

sys.path.append('../../mbspbs10pc')

from mbspbs10pc import utils

# Check MBS-PBS 10% data availability

In [3]:
ROOT = os.path.join('..','..','..','data')

mbs_files = filter(lambda x: x.startswith('MBS'), os.listdir(ROOT))
pbs_files = filter(lambda x: x.startswith('PBS'), os.listdir(ROOT))
sample_pin_lookout = filter(lambda x: x.startswith('SAMPLE'), os.listdir(ROOT))[0]

print('MBS files:')
for mbs in mbs_files:
    print('{}'.format(os.path.join(ROOT, mbs)))
    
print('PBS files:')
for pbs in pbs_files:
    print('{}'.format(os.path.join(ROOT, pbs)))
    
print('Sample PIN lookout: {}'.format(os.path.join(ROOT, sample_pin_lookout)))

MBS files:
../../../data/MBS_SAMPLE_10PCT_2014.csv
../../../data/MBS_SAMPLE_10PCT_2010.csv
../../../data/MBS_SAMPLE_10PCT_2012.csv
../../../data/MBS_SAMPLE_10PCT_2008.csv
../../../data/MBS_SAMPLE_10PCT_2009.csv
../../../data/MBS_SAMPLE_10PCT_2013.csv
../../../data/MBS_SAMPLE_10PCT_2011.csv
PBS files:
../../../data/PBS_SAMPLE_10PCT_2012.csv
../../../data/PBS_SAMPLE_10PCT_2011.csv
../../../data/PBS_SAMPLE_10PCT_2009.csv
../../../data/PBS_SAMPLE_10PCT_2013.csv
../../../data/PBS_SAMPLE_10PCT_2008.csv
../../../data/PBS_SAMPLE_10PCT_2010.csv
Sample PIN lookout: ../../../data/SAMPLE_PIN_LOOKUP.csv

# PBS take a look

In [7]:
filename = pbs_files[0]
df = pd.read_csv(os.path.join(ROOT, '{}'.format(filename)), header=0, index_col=0, nrows=100)

In [8]:
df.shape

(100, 13)

In [9]:
df.head(12)

,SPPLY_DT,ITM_CD,PBS_RGLTN24_ADJST_QTY,BNFT_AMT,PTNT_CNTRBTN_AMT,SRT_RPT_IND,RGLTN24_IND,DRG_TYP_CD,MJR_SPCLTY_GRP_CD,UNDR_CPRSCRPTN_TYP_CD,PRSCRPTN_CNT,PTNT_CTGRY_DRVD_CD,PTNT_STATE
PTNT_ID,,,,,,,,,,,,,
4599420094,11DEC2012,02236Q,30,0.00,16.01,R,N,GE,1,U,1,G2,VIC
5850597601,26NOV2012,08386J,56,72.91,0.00,R,N,GE,1,NaN,1,C0,NSW
1237668038,25FEB2012,08214H,30,22.60,35.40,R,N,GE,1,NaN,1,G2,VIC
4493310342,18JAN2012,02055E,120,18.92,5.80,R,N,GE,1,NaN,1,C1,VIC
2902208774,26DEC2012,02751T,30,11.56,0.00,NaN,N,GE,1,NaN,1,C0,SA
1612941623,04JUL2012,01394J,4,11.29,5.80,R,N,GE,1,NaN,1,C1,SA
1632744498,17MAY2012,03112T,1,17.93,5.80,NaN,N,GE,2,NaN,1,C1,VIC
4718876962,21OCT2012,02236Q,30,0.00,16.01,R,N,GE,1,U,1,G2,VIC
235485777,28AUG2012,08398B,60,12.87,0.00,R,N,GE,2,NaN,1,C0,VIC
87393722,12APR2012,08254K,10,0.00,11.63,NaN,N,GE,1,U,1,G2,VIC
5192147113,29NOV2012,08375T,30,113.67,0.00,R,N,GE,1,NaN,1,C0,QLD
9089833218,02JUN2012,03162K,50,2.05,5.80,NaN,N,GE,2,NaN,1,C1,NSW

Let's make some plots.

In [ ]:
plt.hist(df['SAMPLEWEIGHT'], bins=10)

In [ ]:
utils.show_most_frequent(df['PTNT_STATE'], top_k=8, figsize=(12, 4))